### ISSUE TITLE
Can't extract symvers from the kernel from Android preinstalled on Cubieboard 2

### ISSUE THREAD

**Issue by vi** [glandium/extract-symvers#1]
The file: http://vi-server.org/pub/zImage_from_cubieboard2

The error:

```
$ python /mnt/src/git/extract-symvers/extract-symvers.py -e le -B 0x40000000 zImage  
Traceback (most recent call last):
  File "/mnt/src/git/extract-symvers/extract-symvers.py", line 139, in <module>
    main()
  File "/mnt/src/git/extract-symvers/extract-symvers.py", line 135, in main
    for s, crc, t in kernel.symbols():
  File "/mnt/src/git/extract-symvers/extract-symvers.py", line 102, in symbols
    for t, s in symsearch.items():
AttributeError: 'NoneType' object has no attribute 'items'
```

**Comment by vi** [comment]
Looks like I was using incorrect base address. Retrying with 0xc0008000 produced usable Module.symvers file.

Maybe the tool should detect attempts to use it with incorrect base address and show more friendly message with a list of "typical" base addresses?
